(async () => {
  const $ = id => document.getElementById(id);
  const assert = (ok, message) => { if (!ok) throw new Error(message); };
  const change = (id, value) => { $(id).value = value; $(id).dispatchEvent(new Event('change', { bubbles: true })); };
  const result = document.createElement('pre'); result.id = 'test-result';
  try {
    openGoalModal(null, 'step', 'math');
    assert($('goalOneTime').checked && $('goalScheduleFields').hidden, 'one-time default hides fields');
    $('goalRepeat').click();
    assert(!$('goalScheduleFields').hidden && $('goalDaysField').hidden, 'daily mode displays time and frequency');
    change('goalFrequency', 'weekly');
    assert(!$('goalDaysField').hidden, 'weekly displays days');
    document.querySelector('[data-schedule-day="1"]').click();
    assert(document.querySelector('[data-schedule-day="1"]').getAttribute('aria-pressed') === 'true', 'day toggle');
    change('goalFrequency', 'custom');
    assert(!$('goalDaysField').hidden, 'custom displays days');
    $('goalOneTime').click();
    assert($('goalScheduleFields').hidden, 'one-time hides all schedule inputs');
    $('goalModal').querySelector('[data-close="goalModal"]').click();
    assert(!$('goalModal').open && state.goals.length === 0, 'cancel saves nothing');
    openGoalModal(null, 'arc', 'math');
    assert($('goalRepeatField').hidden && !$('goalRepeat').checked, 'Arc remains non-repeating');
    $('goalModal').close();
    openGoalModal(null, 'step', 'math');
    change('goalTitle', 'Ordinary goal');
    $('goalForm').requestSubmit();
    assert(!state.goals[0].schedule && !state.goals[0].reminder && !state.goals[0].repeatsDaily, 'new one-time Goal saves without new fields');
    openGoalModal(null, 'step', 'math');
    change('goalTitle', 'Scheduled practice');
    $('goalRepeat').click();
    change('goalFrequency', 'weekly');
    assert($('goalSave').disabled && $('goalDaysError').textContent === 'Select at least one day', 'empty days block save');
    document.querySelector('[data-schedule-day="1"]').click();
    assert(!$('goalSave').disabled, 'a weekday allows save');
    document.querySelector('[data-schedule-day="3"]').click();
    document.querySelector('[data-schedule-day="5"]').click();
    Object.defineProperty($('goalTime'), 'value', { configurable: true, get: () => '25:90' });
    $('goalTime').dispatchEvent(new Event('input', { bubbles: true }));
    assert($('goalSave').disabled && $('goalTimeError').textContent === 'Please enter a valid time (HH:MM)', 'inline invalid time blocks save');
    delete $('goalTime').value;
    change('goalTime', '07:00');
    $('goalReminder').click();
    change('goalReminderOffset', '15m');
    $('goalForm').requestSubmit();
    const weekly = state.goals[state.goals.length - 1];
    assert(weekly.schedule.type === 'weekly' && weekly.schedule.time === '07:00' && !weekly.repeatsDaily, 'weekly schedule saved');
    assert(weekly.reminder.enabled && weekly.reminder.offset === '15m', 'reminder saved');
    assert(weekly.schedule.daysOfWeek.join() === '1,3,5', 'Mon/Wed/Fri persist');
    for (const offset of ['0m', '5m', '15m', '30m']) {
      openGoalModal(weekly); change('goalReminderOffset', offset); $('goalForm').requestSubmit();
      assert(weekly.reminder.enabled && weekly.reminder.offset === offset, 'form saves reminder offset ' + offset);
    }
    openGoalModal(weekly);
    assert($('goalRepeat').checked && $('goalTime').value === '07:00', 'edit restores schedule');
    change('goalTime', '08:00');
    $('goalModal').querySelector('[data-close="goalModal"]').click();
    assert(weekly.schedule.time === '07:00', 'cancel edit leaves data intact');
    openGoalModal(weekly);
    $('goalOneTime').click();
    $('goalForm').requestSubmit();
    assert(!weekly.schedule && !weekly.reminder && !weekly.repeatsDaily, 'removing schedule clears reminders');
    const before = state.goals.length;
    assert(!createGoal({ title: 'Invalid', type: 'step', skillId: 'math', xp: 10, schedule: { type: 'daily', time: '25:80' } }), 'invalid time rejected in write path');
    assert(state.goals.length === before && $('goalFormError').textContent === 'Please enter a valid time (HH:MM)', 'invalid input cannot mutate state');
    for (const type of ['daily', 'weekly', 'custom']) {
      openGoalModal(null, 'step', 'math');
      change('goalTitle', type + ' practice');
      $('goalRepeat').click();
      change('goalFrequency', type);
      if (type !== 'daily') document.querySelector('[data-schedule-day="3"]').click();
      $('goalForm').requestSubmit();
      const saved = state.goals[state.goals.length - 1];
      assert(saved.schedule.type === type && !saved.schedule.time, type + ' without time saves');
      assert(saved.repeatsDaily === (type === 'daily'), 'compatibility flag follows daily frequency');
    }
    reminderPanel.render([{ key: 'fixture', goal: { title: '<b>Safe title</b>', xp: 10 }, day: '2026-10-09', time: '07:00', missed: true }]);
    assert($('reminderCount').textContent === '1' && !$('reminderCount').hidden, 'badge shows pending count');
    $('reminderBell').click();
    assert(!$('reminderPanel').hidden && $('reminderBell').getAttribute('aria-expanded') === 'true', 'bell opens panel');
    assert($('reminderList').textContent.includes('Missed') && !$('reminderList').querySelector('b'), 'missed label and safe title');
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }));
    assert($('reminderPanel').hidden && document.activeElement === $('reminderBell'), 'Escape closes and returns focus');
    reminderPanel.render([]);
    const due = new Date(); due.setMinutes(due.getMinutes() - 1);
    const dueTime = `${String(due.getHours()).padStart(2, '0')}:${String(due.getMinutes()).padStart(2, '0')}`;
    createGoal({ title: 'Reminder completion', description: '', type: 'step', skillId: 'math', xp: 10,
      schedule: { type: 'daily', time: dueTime }, reminder: { enabled: true, offset: '0m' } });
    const reminderGoal = state.goals[state.goals.length - 1];
    reminderGoal.createdAt = new Date(Date.now() - 2 * 86400000).toISOString();
    saveState(); reminderSystem.refresh();
    assert(Number($('reminderCount').textContent) >= 1, 'overdue reminder added automatically');
    $('reminderBell').click();
    const mark = [...$('reminderList').querySelectorAll('[data-action="complete"]')].find(button => button.dataset.key.startsWith(reminderGoal.id + '/'));
    const xpBefore = state.skills[0].xp;
    mark.click();
    await new Promise(resolve => setTimeout(resolve, 80));
    assert(reminderGoal.completed && state.skills[0].xp === xpBefore + 10, 'panel Mark done completes and awards XP');
    reminderSystem.refresh();
    assert(!GoalSchedule.pending(state).some(entry => entry.goal.id === reminderGoal.id), 'completed reminder stays dismissed');
    assert(loadState().reminderReceipts[reminderGoal.id].status === 'done', 'completion receipt persisted');
    toggleGoalCompletion(reminderGoal.id, false);
    assert(state.skills[0].xp === xpBefore, 'undo from card reverses reminder reward');
    const pending = GoalSchedule.pending(state).find(entry => entry.goal.id === reminderGoal.id);
    assert(pending, 'manual undo restores reminder');
    reminderSystem.skip(pending);
    assert(state.skills[0].xp === xpBefore && !reminderGoal.completed, 'Skip has no reward');
    assert(!GoalSchedule.pending(loadState()).some(entry => entry.goal.id === reminderGoal.id), 'Skip survives state reload');
    $('reminderClose').click();
    const legacyState = migrateState({ ...state, goals: [{ id: 'old-daily', type: 'step', repeatsDaily: true, title: 'Old daily', skillId: 'math', xp: 10 }] });
    const oldDaily = legacyState.goals[0];
    assert(oldDaily.schedule.type === 'daily' && oldDaily.reminder.offset === '0m', 'old daily migration in browser');
    openGoalModal(oldDaily);
    assert($('goalRepeat').checked && $('goalFrequency').value === 'daily' && !$('goalReminder').checked, 'old daily edit defaults');
    $('goalModal').close();
    const originalSetItem = Storage.prototype.setItem;
    Storage.prototype.setItem = () => { throw new Error('QuotaExceededError'); };
    const savedCount = state.goals.length, savedXp = state.skills[0].xp;
    try {
      assert(!createGoal({ title: 'Storage failure', description: '', type: 'step', skillId: 'math', xp: 10 }), 'failed create returns failure');
      assert(state.goals.length === savedCount && $('storageError'), 'failed create rolls back and explains error');
      assert(!toggleGoalCompletion(state.goals[0].id, true), 'failed completion returns failure');
      assert(state.skills[0].xp === savedXp && !state.goals[0].completed, 'failed completion rolls back XP');
    } finally { Storage.prototype.setItem = originalSetItem; }
    saveState();
    assert(!$('storageError'), 'successful save clears storage error');
    Notification.permission = 'default';
    openGoalModal(null, 'step', 'math');
    change('goalTitle', 'Browser reminder');
    $('goalRepeat').click(); change('goalTime', '23:59');
    $('goalReminder').click();
    await new Promise(resolve => setTimeout(resolve, 20));
    assert(Notification.requests === 1 && Notification.permission === 'granted', 'enabling reminder requests permission');
    assert($('goalNotificationInfo').hidden, 'permission info reflects grant');
    $('goalModal').close();
    const browserGoal = { id: 'browser-goal', type: 'step', skillId: 'math', title: 'System notification', xp: 15,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(), schedule: { type: 'daily', time: dueTime }, reminder: { enabled: true, offset: '0m' } };
    state.goals.push(browserGoal); saveState(); reminderSystem.refresh();
    await new Promise(resolve => setTimeout(resolve, 80));
    const notification = __notifications.find(item => item.title === 'System notification');
    assert(notification && notification.options.body.includes('+15 XP'), 'browser notification includes reward');
    const count = __notifications.length;
    reminderSystem.refresh(); await new Promise(resolve => setTimeout(resolve, 80));
    assert(__notifications.length === count, 'browser deliveries deduplicated');
    notification.onclick();
    assert(document.activeElement.dataset.id === browserGoal.id, 'system notification navigates to Goal');
    Notification.permission = 'denied';
    openGoalModal(browserGoal);
    assert(!$('goalNotificationInfo').hidden && $('goalReminder').checked, 'denied permission keeps in-app reminder enabled');
    $('goalModal').close();
    const pendingBeforeSync = GoalSchedule.pending(state).find(entry => entry.goal.id === browserGoal.id);
    const newerState = JSON.parse(JSON.stringify(state));
    newerState.updatedAt = state.updatedAt + 1;
    newerState.reminderReceipts[browserGoal.id] = { key: pendingBeforeSync.key, status: 'skipped' };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(newerState));
    const beforeStaleAction = state.skills[0].xp;
    reminderSystem.complete(pendingBeforeSync);
    assert(state.skills[0].xp === beforeStaleAction && !GoalSchedule.pending(state).some(entry => entry.key === pendingBeforeSync.key), 'newer tab receipt prevents stale action awarding XP');
    assert(__browserErrors.length === 0, 'no browser errors or warnings: ' + __browserErrors.join('; '));
    assert(document.documentElement.scrollWidth <= innerWidth, 'no page overflow');
    openGoalModal(state.goals.find(goal => goal.schedule?.type === 'custom'));
    assert($('goalModal').scrollWidth <= $('goalModal').clientWidth, 'schedule dialog fits viewport');
    result.hidden = true;
    result.textContent = 'PASS: schedules, validation, migration, storage fallback, reminder actions, browser API and clean console on ' + (isSkillPage ? 'Skill' : 'dashboard');
  } catch (error) { result.textContent = 'FAIL: ' + error.message + '\n' + error.stack; }
  document.body.append(result);
})();
