// Executed by tests/statistics-browser.py in an isolated browser profile.
(() => {
  const assert = (ok, message) => { if (!ok) throw new Error(message); };
  const $ = id => document.getElementById(id);
  try {
    assert(state.skills[0].xp === 100 && state.statisticsStartedOn === getDayKey(), 'legacy migration preserves XP and starts coverage');
    assert(state.completionHistory.length === 0 && state.updatedAt === 17, 'migration does not invent history or update conflict timestamp');
    assert(JSON.parse(localStorage.getItem(STORAGE_KEY)).schemaVersion === 3, 'schema persisted');
    document.querySelector('[data-section="statistics"]').click();
    assert(!$('statisticsPage').hidden && document.querySelector('.dashboard').hidden, 'Statistics navigation');
    assert($('nextWeek').disabled && $('areaEmpty').textContent.includes('3 Life Areas'), 'current week and setup state');
    $('manageLifeAreas').click();
    assert($('lifeAreasModal').open && $('createLifeArea').disabled, 'cannot create empty Area');
    $('lifeAreaName').value = 'Learning';
    const check = $('lifeAreaSkills').querySelector('input');
    check.checked = true;
    check.dispatchEvent(new Event('change', { bubbles: true }));
    assert(!$('createLifeArea').disabled, 'one Skill enables creation');
    $('createLifeAreaForm').requestSubmit();
    assert(state.lifeAreas.length === 1 && state.skills[0].lifeAreaId === state.lifeAreas[0].id, 'Area and assignment saved together');
    $('lifeAreasModal').close();
    createSkill({ name: 'Engineering', goal: '' });
    createSkill({ name: 'Fitness', goal: '' });
    createSkill({ name: 'Uncategorized', goal: '' });
    const firstSkill = state.skills[0];
    const secondSkill = state.skills[1];
    Statistics.createArea(state, 'career', 'Career', [secondSkill.id]);
    Statistics.createArea(state, 'health', 'Health', [state.skills[2].id]);
    createGoal({ title: 'Math practice', description: '', type: 'step', repeatsDaily: true, skillId: firstSkill.id, parentGoalId: '', xp: 30 });
    const goal = state.goals[state.goals.length - 1];
    const tree = document.createElement('ul');
    document.body.append(tree);
    renderGoalTreeNode({ goal, children: [] }, tree);
    const treeMenu = tree.querySelector('.goal-menu-trigger');
    treeMenu.click();
    assert(treeMenu.getAttribute('aria-expanded') === 'true', 'Skill goal overflow menu opens');
    const menuItems = document.querySelectorAll('.goal-menu-item');
    assert([...menuItems].map(item => item.textContent).join() === 'Edit,Delete', 'Skill goal menu contains both actions');
    menuItems[0].click();
    assert($('goalModal').open && $('goalId').value === goal.id, 'Skill goal menu edits the correct goal');
    $('goalModal').close();
    let deleteRequested = false;
    window.confirm = () => { deleteRequested = true; return false; };
    treeMenu.click();
    menuItems[1].click();
    assert(deleteRequested && state.goals.includes(goal), 'Skill goal menu invokes deletion confirmation');
    tree.remove();
    toggleGoalCompletion(goal.id, true);
    assert(firstSkill.xp === 130 && state.completionHistory.length === 1, 'completion awards XP and records once');
    toggleGoalCompletion(goal.id, true);
    assert(firstSkill.xp === 130 && state.completionHistory.length === 1, 'duplicate completion ignored');
    updateGoal(goal.id, { xp: 125, skillId: secondSkill.id });
    toggleGoalCompletion(goal.id, false);
    assert(firstSkill.xp === 100 && secondSkill.xp === 0 && state.completionHistory.length === 0, 'undo reverses original reward and Skill after editing');
    toggleGoalCompletion(goal.id, true);
    assert(secondSkill.xp === 125 && state.completionHistory.length === 1, 'new completion uses edited reward');
    const oldRecord = state.completionHistory[0];
    oldRecord.completionDate = Statistics.shiftDay(getDayKey(), -1);
    goal.completedDay = oldRecord.completionDate;
    render();
    assert(!goal.completed && !goal.activeCompletionId && state.completionHistory.length === 1 && secondSkill.xp === 125, 'daily reset preserves reward history');
    toggleGoalCompletion(goal.id, true);
    assert(secondSkill.xp === 250 && state.completionHistory.length === 2, 'another day earns a new reward');
    window.confirm = () => true;
    window.alert = message => { window.lastAlert = message; };
    deleteSkill(secondSkill.id);
    assert(state.skills.includes(secondSkill) && window.lastAlert, 'Skill with history cannot be deleted');
    deleteGoal(goal.id);
    assert(!state.goals.some(item => item.id === goal.id) && state.completionHistory.length === 2, 'deleting Goal keeps history');
    const start = Statistics.weekStart();
    const assignments = [firstSkill.id, secondSkill.id, state.skills[2].id, state.skills[3].id];
    state.statisticsStartedOn = start;
    state.completionHistory = [500, 300, 200, 900].map((xpAwarded, i) => ({ id: `fixture-${i}`, goalId: `removed-${i}`, skillId: assignments[i], xpAwarded, completionDate: start }));
    saveState();
    render();
    assert($('weeklyGoalCount').textContent === '4 goals', 'weekly count shows goals, not XP');
    assert($('skillProgression').firstElementChild.textContent.includes('Uncategorized'), 'uncategorized Skill leads weekly ranking');
    assert($('areaRadar').querySelector('svg') && $('areaBreakdown').textContent.includes('50%'), 'radar with 50/30/20 shares');
    $('manageLifeAreas').click();
    const assignment = $('skillAreaAssignments').querySelector('select');
    const learningId = firstSkill.lifeAreaId;
    assignment.value = '';
    assignment.dispatchEvent(new Event('change'));
    assert(!firstSkill.lifeAreaId && Statistics.weekly(state, start).categorizedXp === 500, 'assignment UI can uncategorize a Skill');
    const updatedAssignment = $('skillAreaAssignments').querySelector('select');
    updatedAssignment.value = learningId;
    updatedAssignment.dispatchEvent(new Event('change'));
    assert(firstSkill.lifeAreaId === learningId, 'assignment UI restores category');
    const renameForm = $('existingLifeAreas').querySelector('form');
    renameForm.querySelector('input').value = 'Learning renamed';
    renameForm.requestSubmit();
    assert(state.lifeAreas[0].name === 'Learning renamed', 'Area rename UI');
    $('lifeAreasModal').close();
    $('previousWeek').click();
    assert(!$('nextWeek').disabled && !$('areaRadar').querySelector('svg') && !$('skillProgression').children.length, 'all three modules change week');
    $('nextWeek').click();
    assert($('nextWeek').disabled && $('weeklyGoalCount').textContent === '4 goals', 'cannot select a future week');
    const loaded = loadState();
    assert(loaded.updatedAt === state.updatedAt && loaded.completionHistory.length === 4 && loaded.lifeAreas.length === 3, 'local reload preserves all facts and metadata');
    // No XSS from user-provided names in charts or management controls.
    state.lifeAreas[0].name = '<img src=x onerror=alert(1)>';
    render();
    assert(!$('areaBreakdown').querySelector('img'), 'names are rendered as text');
    state.lifeAreas[0].name = 'Learning';
    const historyBeforeDeletion = JSON.stringify(state.completionHistory);
    $('manageLifeAreas').click();
    $('existingLifeAreas').querySelector('.danger').click();
    assert(state.lifeAreas.length === 2 && !firstSkill.lifeAreaId && JSON.stringify(state.completionHistory) === historyBeforeDeletion, 'Area deletion UI preserves history and uncategorizes Skills');
    $('lifeAreasModal').close();
    assert(!$('areaRadar').querySelector('svg') && $('areaEmpty').textContent.includes('3 Life Areas'), 'fewer than three Areas uses setup state');
    Statistics.createArea(state, learningId, 'Learning', [firstSkill.id]);
    state.lifeAreas.sort((a, b) => (a.id === learningId ? -1 : b.id === learningId ? 1 : 0));
    saveState();
    render();
    assert(document.documentElement.scrollWidth <= window.innerWidth, 'no horizontal page overflow');
    const outcome = document.createElement('pre');
    outcome.id = 'test-result';
    outcome.textContent = 'PASS: migration, persistence, navigation, Area creation, completion/undo/edit/reset/delete, weekly charts, future-week guard, safe names';
    outcome.hidden = true;
    document.body.append(outcome);
  } catch (error) {
    const outcome = document.createElement('pre');
    outcome.id = 'test-result';
    outcome.textContent = 'FAIL: ' + error.stack;
    document.body.append(outcome);
  }
})();
